args:
  memory_size:           1_000_000
  nstep:                 3
  diffusion_memory_size: 200_000
  behavior_sample:       16

  noise_std_max:         0.5
  noise_std_min:         0.01
  noise_decay_steps:     1_000_000
  beta_schedule:         "vp"
  n_timesteps:           50

  actor_lr:              1e-4
  critic_lr:             3e-4
  batch_size:            256
  policy_freq:           2
  eval_steps:            250
